const ITEMS_PER_PAGE = 5;
const REQUIRED_MEMBERS = 1000;
const LISTING_FEE_KYTH = 50;
const SLIPPAGE_TOLERANCE_PCT = 0.5;
const DIVORCE_CONFIRM_EXPIRE = 1000 * 60 * 2;
const KISS_COOLDOWN = 3600;

module.exports = {
	ITEMS_PER_PAGE,
	REQUIRED_MEMBERS,
	LISTING_FEE_KYTH,
	SLIPPAGE_TOLERANCE_PCT,
	DIVORCE_CONFIRM_EXPIRE,
	KISS_COOLDOWN,
};
