/**
 * @namespace: addons/economy/helpers/items.js
 * @type: Helper Script
 * @copyright © 2026 kenndeclouv
 * @assistant graa & chaa
 * @version 26.0.0-rc.1
 */

module.exports = {
	utility: [
		{
			id: 'laptop_tech',
			emoji: '💻',
			nameKey: 'economy.shop.items.laptop_tech.name',
			descKey: 'economy.shop.items.laptop_tech.description',
			price: 600,
			buyable: true,
			sellPrice: 300,
		},
		{
			id: 'smartphone_tech',
			emoji: '📱',
			nameKey: 'economy.shop.items.smartphone_tech.name',
			descKey: 'economy.shop.items.smartphone_tech.description',
			price: 800,
			buyable: true,
			sellPrice: 400,
		},
		{
			id: 'pcdesktop_tech',
			emoji: '🖥️',
			nameKey: 'economy.shop.items.pcdesktop_tech.name',
			descKey: 'economy.shop.items.pcdesktop_tech.description',
			price: 1500,
			buyable: true,
			sellPrice: 750,
		},
		{
			id: 'car_vehicle',
			emoji: '🚗',
			nameKey: 'economy.shop.items.car_vehicle.name',
			descKey: 'economy.shop.items.car_vehicle.description',
			price: 25000,
			buyable: true,
			sellPrice: 12500,
		},
		{
			id: 'house_property',
			emoji: '🏠',
			nameKey: 'economy.shop.items.house_property.name',
			descKey: 'economy.shop.items.house_property.description',
			price: 350000,
			buyable: true,
			sellPrice: 175000,
		},
		{
			id: 'company_property',
			emoji: '🏢',
			nameKey: 'economy.shop.items.company_property.name',
			descKey: 'economy.shop.items.company_property.description',
			price: 1000000,
			buyable: true,
			sellPrice: 500000,
		},
		{
			id: 'padlock_item',
			emoji: '🔒',
			nameKey: 'economy.shop.items.padlock_item.name',
			descKey: 'economy.shop.items.padlock_item.description',
			price: 15,
			buyable: true,
			sellPrice: 7,
		},
		{
			id: 'fakewallet_item',
			emoji: '👛',
			nameKey: 'economy.shop.items.fakewallet_item.name',
			descKey: 'economy.shop.items.fakewallet_item.description',
			price: 20,
			buyable: true,
			sellPrice: 10,
		},
		{
			id: 'antivirus_item',
			emoji: '🛡️',
			nameKey: 'economy.shop.items.antivirus_item.name',
			descKey: 'economy.shop.items.antivirus_item.description',
			price: 50,
			buyable: true,
			sellPrice: 25,
		},
		{
			id: 'bicycle_vehicle',
			emoji: '🚲',
			nameKey: 'economy.shop.items.bicycle_vehicle.name',
			descKey: 'economy.shop.items.bicycle_vehicle.description',
			price: 300,
			buyable: true,
			sellPrice: 150,
		},
		{
			id: 'motorcycle_vehicle',
			emoji: '🏍️',
			nameKey: 'economy.shop.items.motorcycle_vehicle.name',
			descKey: 'economy.shop.items.motorcycle_vehicle.description',
			price: 3000,
			buyable: true,
			sellPrice: 1500,
		},
		{
			id: 'camera_tech',
			emoji: '📸',
			nameKey: 'economy.shop.items.camera_tech.name',
			descKey: 'economy.shop.items.camera_tech.description',
			price: 800,
			buyable: true,
			sellPrice: 400,
		},
		{
			id: 'microphone_tech',
			emoji: '🎙️',
			nameKey: 'economy.shop.items.microphone_tech.name',
			descKey: 'economy.shop.items.microphone_tech.description',
			price: 150,
			buyable: true,
			sellPrice: 75,
		},
		{
			id: 'briefcase_item',
			emoji: '💼',
			nameKey: 'economy.shop.items.briefcase_item.name',
			descKey: 'economy.shop.items.briefcase_item.description',
			price: 100,
			buyable: true,
			sellPrice: 50,
		},
		{
			id: 'bankvault_item',
			emoji: '🏦',
			nameKey: 'economy.shop.items.bankvault_item.name',
			descKey: 'economy.shop.items.bankvault_item.description',
			price: 5000,
			buyable: true,
			sellPrice: 2500,
		},
		{
			id: 'cctv_item',
			emoji: '📹',
			nameKey: 'economy.shop.items.cctv_item.name',
			descKey: 'economy.shop.items.cctv_item.description',
			price: 300,
			buyable: true,
			sellPrice: 150,
		},
		{
			id: 'policecruiser_item',
			emoji: '🚓',
			nameKey: 'economy.shop.items.policecruiser_item.name',
			descKey: 'economy.shop.items.policecruiser_item.description',
			price: 50000,
			buyable: true,
			sellPrice: 25000,
		},
		{
			id: 'taser_item',
			emoji: '🔫',
			nameKey: 'economy.shop.items.taser_item.name',
			descKey: 'economy.shop.items.taser_item.description',
			price: 2000,
			buyable: true,
			sellPrice: 1000,
		},
	],
	robbing: [
		{
			id: 'poison_item',
			emoji: '🧪',
			nameKey: 'economy.shop.items.poison_item.name',
			descKey: 'economy.shop.items.poison_item.description',
			price: 25,
			buyable: true,
			sellPrice: 12,
		},
		{
			id: 'guard_item',
			emoji: '🚓',
			nameKey: 'economy.shop.items.guard_item.name',
			descKey: 'economy.shop.items.guard_item.description',
			price: 150,
			buyable: true,
			sellPrice: 75,
		},
		{
			id: 'bounty_license_item',
			emoji: '🕵️',
			nameKey: 'economy.shop.items.bounty_license_item.name',
			descKey: 'economy.shop.items.bounty_license_item.description',
			price: 1000,
			buyable: true,
			sellPrice: 500,
		},
		{
			id: 'stealth_suit_item',
			emoji: '🥷',
			nameKey: 'economy.shop.items.stealth_suit_item.name',
			descKey: 'economy.shop.items.stealth_suit_item.description',
			price: 2000,
			buyable: true,
			sellPrice: 1000,
		},
		{
			id: 'lockpick_item',
			emoji: '🪛',
			nameKey: 'economy.shop.items.lockpick_item.name',
			descKey: 'economy.shop.items.lockpick_item.description',
			price: 50,
			buyable: true,
			sellPrice: 25,
		},
		{
			id: 'smokegrenade_item',
			emoji: '💨',
			nameKey: 'economy.shop.items.smokegrenade_item.name',
			descKey: 'economy.shop.items.smokegrenade_item.description',
			price: 100,
			buyable: true,
			sellPrice: 50,
		},
		{
			id: 'lawyer_contact_item',
			emoji: '👔',
			nameKey: 'economy.shop.items.lawyer_contact_item.name',
			descKey: 'economy.shop.items.lawyer_contact_item.description',
			price: 500,
			buyable: true,
			sellPrice: 250,
		},
	],
	pet: [
		{
			id: 'petfood_item',
			emoji: '🍪',
			nameKey: 'economy.shop.items.petfood_item.name',
			descKey: 'economy.shop.items.petfood_item.description',
			price: 5,
			buyable: true,
			sellPrice: 2,
		},
	],
	merriage: [
		{
			id: 'merriage_ring',
			emoji: '💍',
			nameKey: 'economy.shop.items.merriage_ring.name',
			descKey: 'economy.shop.items.merriage_ring.description',
			price: 2500,
			buyable: true,
			sellPrice: 1250,
		},
	],
	consumables: [
		{
			id: 'coffee_item',
			emoji: '☕',
			nameKey: 'economy.shop.items.coffee_item.name',
			descKey: 'economy.shop.items.coffee_item.description',
			price: 5,
			buyable: true,
			sellPrice: 2,
		},
		{
			id: 'energydrink_item',
			emoji: '🥫',
			nameKey: 'economy.shop.items.energydrink_item.name',
			descKey: 'economy.shop.items.energydrink_item.description',
			price: 3,
			buyable: true,
			sellPrice: 1,
		},
		{
			id: 'lotteryticket_item',
			emoji: '🎫',
			nameKey: 'economy.shop.items.lotteryticket_item.name',
			descKey: 'economy.shop.items.lotteryticket_item.description',
			price: 10,
			buyable: true,
			sellPrice: 5,
		},
	],
	lifestyle: [
		{
			id: 'goldbar_item',
			emoji: '🪙',
			nameKey: 'economy.shop.items.goldbar_item.name',
			descKey: 'economy.shop.items.goldbar_item.description',
			price: 2000,
			buyable: true,
			sellPrice: 1000,
		},
		{
			id: 'designerwatch_item',
			emoji: '⌚',
			nameKey: 'economy.shop.items.designerwatch_item.name',
			descKey: 'economy.shop.items.designerwatch_item.description',
			price: 15000,
			buyable: true,
			sellPrice: 7500,
		},
		{
			id: 'yacht_vehicle',
			emoji: '🛥️',
			nameKey: 'economy.shop.items.yacht_vehicle.name',
			descKey: 'economy.shop.items.yacht_vehicle.description',
			price: 2500000,
			buyable: true,
			sellPrice: 1250000,
		},
		{
			id: 'privatejet_vehicle',
			emoji: '🛩️',
			nameKey: 'economy.shop.items.privatejet_vehicle.name',
			descKey: 'economy.shop.items.privatejet_vehicle.description',
			price: 5000000,
			buyable: true,
			sellPrice: 2500000,
		},
	],
};
