/**
 * @namespace: addons/economy/helpers/items.js
 * @type: Helper Script
 * @copyright © 2026 kenndeclouv
 * @assistant graa & chaa
 * @version 1.0.0-rc
 */

module.exports = {
	utility: [
		{
			id: 'laptop_tech',
			emoji: '💻',
			nameKey: 'economy.shop.items.laptop_tech.name',
			descKey: 'economy.shop.items.laptop_tech.description',
			price: 1000,
			buyable: true,
			sellPrice: 500,
		},
		{
			id: 'smartphone_tech',
			emoji: '📱',
			nameKey: 'economy.shop.items.smartphone_tech.name',
			descKey: 'economy.shop.items.smartphone_tech.description',
			price: 700,
			buyable: true,
			sellPrice: 350,
		},
		{
			id: 'pcdesktop_tech',
			emoji: '🖥️',
			nameKey: 'economy.shop.items.pcdesktop_tech.name',
			descKey: 'economy.shop.items.pcdesktop_tech.description',
			price: 2000,
			buyable: true,
			sellPrice: 1000,
		},
		{
			id: 'car_vehicle',
			emoji: '🚗',
			nameKey: 'economy.shop.items.car_vehicle.name',
			descKey: 'economy.shop.items.car_vehicle.description',
			price: 30000,
			buyable: true,
			sellPrice: 15000,
		},
		{
			id: 'house_property',
			emoji: '🏠',
			nameKey: 'economy.shop.items.house_property.name',
			descKey: 'economy.shop.items.house_property.description',
			price: 400000,
			buyable: true,
			sellPrice: 200000,
		},
		{
			id: 'company_property',
			emoji: '🏢',
			nameKey: 'economy.shop.items.company_property.name',
			descKey: 'economy.shop.items.company_property.description',
			price: 700000,
			buyable: true,
			sellPrice: 350000,
		},
		{
			id: 'padlock_item',
			emoji: '🔒',
			nameKey: 'economy.shop.items.padlock_item.name',
			descKey: 'economy.shop.items.padlock_item.description',
			price: 5000,
			buyable: true,
			sellPrice: 2500,
		},
		{
			id: 'fakewallet_item',
			emoji: '👛',
			nameKey: 'economy.shop.items.fakewallet_item.name',
			descKey: 'economy.shop.items.fakewallet_item.description',
			price: 15000,
			buyable: true,
			sellPrice: 7500,
		},
		{
			id: 'antivirus_item',
			emoji: '🛡️',
			nameKey: 'economy.shop.items.antivirus_item.name',
			descKey: 'economy.shop.items.antivirus_item.description',
			price: 25000,
			buyable: true,
			sellPrice: 12500,
		},
	],
	robbing: [
		{
			id: 'poison_item',
			emoji: '🧪',
			nameKey: 'economy.shop.items.poison_item.name',
			descKey: 'economy.shop.items.poison_item.description',
			price: 40,
			buyable: true,
			sellPrice: 15,
		},
		{
			id: 'guard_item',
			emoji: '🚓',
			nameKey: 'economy.shop.items.guard_item.name',
			descKey: 'economy.shop.items.guard_item.description',
			price: 100,
			buyable: true,
			sellPrice: 50,
		},
		{
			id: 'bounty_license_item',
			emoji: '🕵️',
			nameKey: 'economy.shop.items.bounty_license_item.name',
			descKey: 'economy.shop.items.bounty_license_item.description',
			price: 50000,
			buyable: true,
			sellPrice: 25000,
		},
		{
			id: 'stealth_suit_item',
			emoji: '🥷',
			nameKey: 'economy.shop.items.stealth_suit_item.name',
			descKey: 'economy.shop.items.stealth_suit_item.description',
			price: 35000,
			buyable: true,
			sellPrice: 17500,
		},
	],
	pet: [
		{
			id: 'petfood_item',
			emoji: '🍪',
			nameKey: 'economy.shop.items.petfood_item.name',
			descKey: 'economy.shop.items.petfood_item.description',
			price: 10,
			buyable: true,
			sellPrice: 4,
		},
	],
	merriage: [
		{
			id: 'merriage_ring',
			emoji: '💍',
			nameKey: 'economy.shop.items.merriage_ring.name',
			descKey: 'economy.shop.items.merriage_ring.description',
			price: 5200,
			buyable: true,
			sellPrice: 800,
		},
	],
};
