/**
 * @file setup/writer.js
 * @description Generates .env and kythia.config.js by patching the example
 *              template files with wizard answers.
 * @copyright © 2026 kenndeclouv
 */

/** biome-ignore-all lint/suspicious/noConsole: not the bot log, ignore console warn */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const TEMPLATE_ENV = path.join(ROOT, 'example.env');
const TEMPLATE_CFG = path.join(ROOT, 'example.kythia.config.js');

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Set a KEY="value" pair in an .env string.
 * Handles both quoted and unquoted existing values (or missing keys).
 * If the key is already present it is updated in-place; otherwise it is
 * appended at the end.
 */
function setEnvKey(content, key, value) {
	const escaped = String(value ?? '')
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"');
	// Match: KEY="..." or KEY=value (no quotes) — optionally with inline comment
	const re = new RegExp(`^(${key}=)("?)[^"\\n]*\\2([^\\n]*)`, 'm');
	if (re.test(content)) {
		return content.replace(re, `$1"${escaped}"$3`);
	}
	// Key not found – append
	return `${content}\n${key}="${escaped}"`;
}

/**
 * Replace a JS string literal value in a source file.
 * Targets patterns like:   key: 'old_value',
 *                          key: "old_value",
 *                          key: false,
 *                          key: true,
 *                          key: 123,
 * Only replaces the *first* occurrence of `key:` that follows a newline +
 * optional whitespace (to avoid partial matches inside comments etc.).
 */
function setJsStringKey(content, key, newValue) {
	// Match the key followed by a colon and any JS literal value
	const re = new RegExp(
		`(\\b${key}:\\s*)('(?:[^'\\\\]|\\\\.)*'|"(?:[^"\\\\]|\\\\.)*"|true|false|\\d+)`,
		'',
	);
	const replacement =
		typeof newValue === 'string'
			? `$1'${newValue.replace(/'/g, "\\'")}'`
			: `$1${newValue}`;
	return content.replace(re, replacement);
}

/**
 * Replace every JS boolean literal that follows `key:` (first occurrence).
 */
function setJsBool(content, key, bool) {
	const re = new RegExp(`(\\b${key}:\\s*)(true|false)`);
	return content.replace(re, `$1${bool}`);
}

/**
 * Replace a JS array literal that follows `key:` (first occurrence).
 */
function setJsArray(content, key, items) {
	const re = new RegExp(`(\\b${key}:\\s*)\\[[^\\]]*\\]`);
	const arr = `[${items.map((i) => `'${i.replace(/'/g, "\\'")}'`).join(', ')}]`;
	return content.replace(re, `$1${arr}`);
}

// ── .env builder ─────────────────────────────────────────────────────────────

/**
 * Builds the .env content by:
 *   1. Loading example.env as the base template
 *   2. Patching in the wizard-collected values
 *   3. Appending per-addon env vars from each addon's toEnv() function
 */
function buildEnv(answers) {
	const { license, bot, db, redis, addons } = answers;

	if (!fs.existsSync(TEMPLATE_ENV)) {
		throw new Error(`Template not found: ${TEMPLATE_ENV}`);
	}

	let env = fs.readFileSync(TEMPLATE_ENV, 'utf8');

	// Rewrite the header comment to reflect generation
	env = env.replace(
		/^(# ={3,}\n#\s+KYTHIA BOT CONFIGURATION[\s\S]*?# ={3,})/m,
		[
			'# ===================================================================',
			'#                    KYTHIA BOT CONFIGURATION',
			'#           Generated by: node setup.js | bun setup.js',
			`#           Generated at: ${new Date().toISOString()}`,
			'# ===================================================================',
		].join('\n'),
	);

	// ── Quick start ───────────────────────────────────────────────────────
	env = setEnvKey(env, 'LICENSE_KEY', license.licenseKey ?? '');
	env = setEnvKey(env, 'DISCORD_BOT_TOKEN', bot.token ?? '');
	env = setEnvKey(env, 'DISCORD_BOT_CLIENT_ID', bot.clientId ?? '');
	env = setEnvKey(env, 'DISCORD_BOT_CLIENT_SECRET', bot.clientSecret ?? '');

	// ── Database ──────────────────────────────────────────────────────────
	if (db.driver === 'sqlite') {
		env = setEnvKey(env, 'DB_DRIVER', 'sqlite');
		env = setEnvKey(env, 'DB_NAME', db.dbName || 'kythia.sqlite');
	} else {
		env = setEnvKey(env, 'DB_DRIVER', db.driver ?? '');
		env = setEnvKey(env, 'DB_HOST', db.dbHost || 'localhost');
		env = setEnvKey(env, 'DB_PORT', db.dbPort || '3306');
		env = setEnvKey(env, 'DB_NAME', db.dbName || 'kythia');
		env = setEnvKey(env, 'DB_USER', db.dbUser || 'root');
		env = setEnvKey(env, 'DB_PASSWORD', db.dbPass || '');
	}

	// ── Redis ─────────────────────────────────────────────────────────────
	env = setEnvKey(env, 'REDIS_URLS', redis.redisUrls ?? '');

	// ── Monitoring ────────────────────────────────────────────────────────
	env = setEnvKey(env, 'SENTRY_DSN', '');

	// ── Per-addon toEnv() contributions ──────────────────────────────────
	const stepsDir = path.join(__dirname, 'steps/addons');
	const addonEnvGroups = [];

	for (const [addonName, addonResult] of Object.entries(addons)) {
		if (!addonResult?.enabled) continue;

		const stepFile = path.join(stepsDir, `${addonName}.js`);
		if (!fs.existsSync(stepFile)) continue;

		try {
			const stepModule = require(stepFile);
			if (typeof stepModule.toEnv === 'function') {
				const envVars = stepModule.toEnv(addonResult);
				addonEnvGroups.push({ addonName, envVars });
			}
		} catch (_e) {
			// Skip if module fails to load
		}
	}

	if (addonEnvGroups.length > 0) {
		const lines = ['', '# ── Addon-specific values set by setup wizard ──'];
		for (const { addonName, envVars } of addonEnvGroups) {
			lines.push(`# ── ${addonName} ──`);
			for (const [key, val] of Object.entries(envVars)) {
				env = setEnvKey(env, key, val);
				lines.push(`# ${key} updated above`);
			}
		}
		// Append the comment block so the user can see what was patched
		env += `${lines.join('\n')}\n`;
	}

	return env;
}

// ── kythia.config.js builder ─────────────────────────────────────────────────

/**
 * Builds kythia.config.js by:
 *   1. Loading example.kythia.config.js as the base template
 *   2. Patching in the wizard-collected values
 *   3. Updating the file header to reflect generation
 */
function buildConfig(answers) {
	const { license, bot, _db, redis, addons } = answers;

	if (!fs.existsSync(TEMPLATE_CFG)) {
		throw new Error(`Template not found: ${TEMPLATE_CFG}`);
	}

	let cfg = fs.readFileSync(TEMPLATE_CFG, 'utf8');

	// ── Rewrite the top block comment to show this is generated ──────────
	cfg = cfg.replace(
		/\/\*\*[\s\S]*?\*\//,
		[
			'/**',
			' * @file kythia.config.js',
			' * @description Kythia Bot Configuration',
			' * @generated by: node setup.js | bun setup.js',
			` * @generated at: ${new Date().toISOString()}`,
			' * @copyright © 2026 kenndeclouv',
			' */',
		].join('\n'),
	);

	// ── Legal ─────────────────────────────────────────────────────────────
	cfg = setJsBool(cfg, 'acceptTOS', license.acceptTOS);
	cfg = setJsBool(cfg, 'dataCollection', license.dataCollection);

	// ── Owner ─────────────────────────────────────────────────────────────
	cfg = setJsStringKey(cfg, 'ids', bot.ownerIds ?? '');
	cfg = setJsStringKey(cfg, 'names', bot.ownerNames ?? '');

	// ── Bot ───────────────────────────────────────────────────────────────
	cfg = setJsStringKey(cfg, 'name', bot.botName || 'Kythia');
	cfg = setJsStringKey(cfg, 'color', bot.color || '#FFFFFF');
	cfg = setJsStringKey(cfg, 'status', bot.status || 'online');
	cfg = setJsStringKey(cfg, 'activityType', bot.activityType || 'Playing');
	cfg = setJsStringKey(cfg, 'activity', bot.activity || '');
	cfg = setJsStringKey(cfg, 'timezone', bot.timezone || 'Asia/Jakarta');

	// prefixes array
	if (bot.prefixes) {
		const prefixList = bot.prefixes
			.split(',')
			.map((p) => p.trim())
			.filter(Boolean);
		cfg = setJsArray(cfg, 'prefixes', prefixList);
	}

	// ── Database – useRedis flag ──────────────────────────────────────────
	cfg = setJsBool(cfg, 'useRedis', redis.useRedis !== false);

	// ── Addons – active flags ─────────────────────────────────────────────
	// Walk through every known addon name and set `active:` accordingly.
	// We do this by keying on the camelCase name that appears in the config.
	const addonMap = {
		activity: 'activity',
		adventure: 'adventure',
		ai: 'ai',
		api: 'api',
		automod: 'automod',
		autoreact: 'autoreact',
		autoreply: 'autoreply',
		birthday: 'birthday',
		booster: 'booster',
		checklist: 'checklist',
		economy: 'economy',
		'embed-builder': 'embedBuilder',
		fun: 'fun',
		giveaway: 'giveaway',
		globalchat: 'globalchat',
		globalvoice: 'globalvoice',
		image: 'image',
		invite: 'invite',
		leveling: 'leveling',
		minecraft: 'minecraft',
		modmail: 'modmail',
		music: 'music',
		nsfw: 'nsfw',
		pet: 'pet',
		pro: 'pro',
		quest: 'quest',
		'reaction-role': 'reactionRole',
		server: 'server',
		'social-alerts': 'socialAlerts',
		streak: 'streak',
		tempvoice: 'tempvoice',
		ticket: 'ticket',
		verification: 'verification',
		welcomer: 'welcomer',
	};

	for (const [rawName, camelName] of Object.entries(addonMap)) {
		const result = addons[rawName] ?? addons[camelName] ?? {};
		const enabled = result?.enabled !== false;

		// Replace the `active: <bool>` inside the addon block.
		// Strategy: find the addon key in the config, then replace the very
		// next `active:` occurrence after it.
		const addonKeyRe = new RegExp(
			`(\\b${camelName}:\\s*\\{[^}]*?active:\\s*)(true|false)`,
			's',
		);
		cfg = cfg.replace(addonKeyRe, `$1${enabled}`);
	}

	return cfg;
}

// ── File writer ───────────────────────────────────────────────────────────────

/**
 * Write both config files to the project root.
 */
function writeFiles(answers) {
	const envPath = path.join(ROOT, '.env');
	const configPath = path.join(ROOT, 'kythia.config.js');

	const envBackup = `${envPath}.backup`;
	const configBackup = `${configPath}.backup`;

	// Back up existing files
	if (fs.existsSync(envPath)) fs.copyFileSync(envPath, envBackup);
	if (fs.existsSync(configPath)) fs.copyFileSync(configPath, configBackup);

	fs.writeFileSync(envPath, buildEnv(answers), 'utf8');
	fs.writeFileSync(configPath, buildConfig(answers), 'utf8');

	return { envPath, configPath, envBackup, configBackup };
}

module.exports = { writeFiles, buildEnv, buildConfig };
